# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdg" do
  name "gdg"
  desc "Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting backup/restore to local filesystem, s3, gcs, azure, and other S3 compatible storage engines."
  homepage "https://software.es.net/gdg"
  version "0.9.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdg"

  on_macos do
    url "https://github.com/esnet/gdg/releases/download/v#{version}/gdg_Darwin_all.tar.gz"
    sha256 "2174ae2c92a31058283873e5093a5f82ce44ed25b7ce95282341cb3cc99b235e"
  end

  on_linux do
    on_intel do
      url "https://github.com/esnet/gdg/releases/download/v#{version}/gdg_Linux_x86_64.tar.gz"
      sha256 "eade9b07a3f8ad01787715f93f1966b32301f5baf7d827d52d6b16dd4dfb8613"
    end
    on_arm do
      url "https://github.com/esnet/gdg/releases/download/v#{version}/gdg_Linux_arm64.tar.gz"
      sha256 "3a5b1c90df74da2bcf77890d58c4848b69c8c1ea30378021db8689bafb8fb565"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdg"]
    end
  end

  # No zap stanza required
end
