# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdg" do
  desc "Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting backup/restore to local filesystem, s3, gcs, azure, and other S3 compatible storage engines."
  homepage "https://software.es.net/gdg"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdg"

  on_macos do
    url "https://github.com/esnet/gdg/releases/download/v0.8.1/gdg_Darwin_all.tar.gz"
    sha256 "c0c658eeb169c9103872d9e9a2b179b295ba5bf022a08a8cd5b607271a665e9f"
  end

  on_linux do
    on_intel do
      url "https://github.com/esnet/gdg/releases/download/v0.8.1/gdg_Linux_x86_64.tar.gz"
      sha256 "dd873b97e1748ed6b49d7045ae5026673cb94da754d60aa186c2a41e796612be"
    end
    on_arm do
      url "https://github.com/esnet/gdg/releases/download/v0.8.1/gdg_Linux_arm64.tar.gz"
      sha256 "34d785fe20288d7ff9ab4dc44f6b1ebfce06eced39ada332d27f91b5dd2cd61f"
    end
  end

  conflicts_with formula: [
      "gdg",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdg"]
    end
  end

  # No zap stanza required
end
