# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdg" do
  name "gdg"
  desc "Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting backup/restore to local filesystem, s3, gcs, azure, and other S3 compatible storage engines."
  homepage "https://software.es.net/gdg"
  version "0.9.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdg"

  on_macos do
    url "https://github.com/esnet/gdg/releases/download/v#{version}/gdg_Darwin_all.tar.gz"
    sha256 "8a26394dc48cf08f51ab38f3b9372fb85a2408254c7fe96b53a1e79a262ee28d"
  end

  on_linux do
    on_intel do
      url "https://github.com/esnet/gdg/releases/download/v#{version}/gdg_Linux_x86_64.tar.gz"
      sha256 "57e1c190823b336294a8bdc0b0f10ae4c58f73f74764adfd589e046cca3b6e7b"
    end
    on_arm do
      url "https://github.com/esnet/gdg/releases/download/v#{version}/gdg_Linux_arm64.tar.gz"
      sha256 "4027e3869be106cdfbd4bb0b02a2729d024516f7d40c6cadb7df9333414367b6"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdg"]
    end
  end

  # No zap stanza required
end
