# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdg < Formula
  desc "Grafana Dash-n-Grab (GDG) -- Dashboard/DataSource Manager for grafana supporting backup/restore to local filesystem, s3, gcs, azure, and other S3 compatible storage engines."
  homepage "https://software.es.net/gdg"
  version "0.7.1"

  on_macos do
    url "https://github.com/esnet/gdg/releases/download/v0.7.1/gdg_Darwin_all.tar.gz"
    sha256 "9719c1d09172d56516f23c8e3405f9e550cc1173f651182aa8a59b1f91db2f81"

    def install
      bin.install "gdg"
      bin.install "gdg-generate"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/esnet/gdg/releases/download/v0.7.1/gdg_Linux_x86_64.tar.gz"
        sha256 "052b32013d529628f14b3e69fff2e4e0ca68a732e4b925d58fedeafbc23245cc"

        def install
          bin.install "gdg"
          bin.install "gdg-generate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/esnet/gdg/releases/download/v0.7.1/gdg_Linux_arm64.tar.gz"
        sha256 "68eeab8e6093a621a4467f942b762f01a432d501d0d362f0d3d8a5421a9917d2"

        def install
          bin.install "gdg"
          bin.install "gdg-generate"
        end
      end
    end
  end
end
